Repository Jedisjeux/ReactNative, pull requests merged in 2018-03, with the labels that each got.

#5 [Products] Init product pages
  .gitignore
  App.js
  app.json
  package.json
  src/assets/Style.js
  src/assets/expo.symbol.white.png
  src/assets/icons/home.png
  src/assets/icons/user.png
  src/components/product/ProductCellComponent.js
  src/screens/AboutScreen.js
  src/screens/ProductDetailsScreen.js
  src/screens/ProductsScreen.js
  yarn.lock
Labels: Feature

#8 Init/redux
  App.js
  package.json
  src/actions/ProductsActions.js
  src/constants/ProductsConstants.js
  src/reducers/ProductsReducer.js
  src/reducers/index.js
  src/screens/ProductsScreen.js
  src/services/ProductService.js
  store.js
  yarn.lock
Labels: Feature

#9 Refactor ProductStackNavigator
  App.js
  src/navigators/ProductStackNavigator.js
  src/screens/ProductsScreen.js
Labels: DX, Enhancement

#11 image cover
  src/screens/ProductDetailsScreen.js
Labels: Enhancement

#12 Refreshing products
  src/screens/ProductDetailsScreen.js
  src/screens/ProductsScreen.js
Labels: Enhancement, Feature

#7 init config for several environments
  .babelrc
  .env.dist
  .gitignore
  android/app/BUCK
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/jedisjeuxreactnative/MainActivity.java
  android/app/src/main/java/com/jedisjeuxreactnative/MainApplication.java
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/keystores/BUCK
  android/keystores/debug.keystore.properties
  android/settings.gradle
  app.json
  index.js
  ios/JedisjeuxReactNative-tvOS/Info.plist
  ios/JedisjeuxReactNative-tvOSTests/Info.plist
  ios/JedisjeuxReactNative.xcodeproj/project.pbxproj
  ios/JedisjeuxReactNative.xcodeproj/xcshareddata/xcschemes/JedisjeuxReactNative-tvOS.xcscheme
  ios/JedisjeuxReactNative.xcodeproj/xcshareddata/xcschemes/JedisjeuxReactNative.xcscheme
  ios/JedisjeuxReactNative/AppDelegate.h
  ios/JedisjeuxReactNative/AppDelegate.m
  ios/JedisjeuxReactNative/Base.lproj/LaunchScreen.xib
  ios/JedisjeuxReactNative/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/JedisjeuxReactNative/Images.xcassets/Contents.json
  ios/JedisjeuxReactNative/Info.plist
  ios/JedisjeuxReactNative/main.m
  ios/JedisjeuxReactNativeTests/Info.plist
  ios/JedisjeuxReactNativeTests/JedisjeuxReactNativeTests.m
  package.json
  src/services/ProductService.js
  yarn.lock
Labels: Feature

#13 [API] https for base url
  .env.dist
Labels: Bug
